return {}
-- return {
-- 	"yetone/avante.nvim",
-- 	build = vim.fn.has("win32") ~= 0 and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
-- 		or "make",
-- 	event = "VeryLazy",
-- 	version = false,
--
-- 	---@type avante.Config
-- 	opts = {
-- 		provider = "gpt_5_mini", -- use GPT-5 by default
-- 		mode = "agentic", -- optional; keep Avante’s tool mode
--
-- 		-- Nice UX: use Snacks for input + file picker
-- 		input = {
-- 			provider = "snacks",
-- 			provider_opts = { title = "Avante", icon = " " },
-- 		},
-- 		selector = {
-- 			provider = "snacks", -- avoids the buggy native selector
-- 			provider_opts = {},
-- 		},
-- 		behaviour = {
-- 			enable_fastapply = true, -- Enable Fast Apply feature
-- 		},
-- 		providers = {
-- 			-- base provider config (real provider)
-- 			openai = {
-- 				endpoint = "https://api.openai.com/v1",
-- 				api_key_name = "OPENAI_API_KEY",
-- 				model = "gpt-5-mini", -- default model for this base
-- 				extra_request_body = {
-- 					temperature = 1,
-- 				},
-- 			},
--
-- 			-- alias 1: GPT-5 full
-- 			gpt_5 = {
-- 				__inherited_from = "openai",
-- 				model = "gpt-5",
-- 			},
--
-- 			-- alias 2: GPT-5 mini (faster/cheaper)
-- 			gpt_5_mini = {
-- 				__inherited_from = "openai",
-- 				model = "gpt-5-mini",
-- 			},
-- 		},
-- 	},
--
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		"folke/snacks.nvim", -- input + selector
-- 		"nvim-tree/nvim-web-devicons",
-- 		{
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = { insert_mode = true },
-- 					use_absolute_path = true,
-- 				},
-- 			},
-- 		},
-- 		{
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = { file_types = { "markdown", "Avante" } },
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- }
