return {
    --     "iabdelkareem/csharp.nvim",
    --     dependencies = {
    --         "williamboman/mason.nvim", -- Required, automatically installs omnisharp
    --         "mfussenegger/nvim-dap",
    --         "Tastyep/structlog.nvim",  -- Optional, but highly recommended for debugging
    --     },
    --     config = function()
    --         require("csharp").setup()
    --         vim.keymap.set('n', '<leader>rr', require("csharp").run_project, { desc = "Run csharp project" })
    --         vim.keymap.set('n', '<leader>rd', require("csharp").debug_project, { desc = "Debug csharp project" })
    --
    --         -- Configure nvim-dap
    --         local dap = require('dap')
    --         local ui = require('dapui')
    --         dap.set_log_level('DEBUG')
    --
    --         dap.adapters.coreclr = {
    --             type = 'executable',
    --             command = '/home/noahbalboa66/programs/netcoredbg/netcoredbg',
    --             args = { '--interpreter=vscode' }
    --         }
    --
    --         dap.configurations.cs = {
    --             {
    --                 type = 'coreclr',
    --                 name = 'launch - netcoredbg',
    --                 request = 'launch',
    --                 program = function()
    --                     return vim.fn.input('Path to dll: ', vim.fn.getcwd() .. '/bin/Debug/', 'file')
    --                 end,
    --             },
    --             {
    --                 type = 'coreclr',
    --                 name = 'attach - netcoredbg',
    --                 request = 'attach',
    --                 processId = function()
    --                     return vim.fn.input('Process ID: ')
    --                 end,
    --             },
    --         }
    --
    --         -- Optional: Add more keybindings for debugging
    --         vim.keymap.set('n', '<leader>gb', dap.toggle_breakpoint, { desc = "Toggle Breakpoint" })
    --         vim.keymap.set('n', '<leader>gc', dap.continue, { desc = "Continue Debugging" })
    --         vim.keymap.set('n', '<leader>gi', dap.step_into, { desc = "Step Into" })
    --         vim.keymap.set('n', '<leader>go', dap.step_over, { desc = "Step Over" })
    --         vim.keymap.set('n', '<leader>gu', dap.step_out, { desc = "Step Out" })
    --
    --         vim.keymap.set('n', '<leader>g?', function()
    --             require('dapui').eval(nil, { enter = true })
    --         end, { desc = "Eval" })
    --
    --         dap.listeners.before.attach.dapui_config = function()
    --             ui.open()
    --         end
    --         dap.listeners.before.launch.dapui_config = function()
    --             ui.open()
    --         end
    --         dap.listeners.before.event_terminated.dapui_config = function()
    --             ui.close()
    --         end
    --         dap.listeners.before.event_exited.dapui_config = function()
    --             ui.close()
    --         end
    --     end
}
